---
work_path: ./work
log_level: SUCCESS

scratchpad:
  release: "24.12-uo_test-3"
steps:
  hello:
    - name: hello_world bla bla
  download_data:
    - name: sync_bucket etl output files
      source: gs://open-targets-pre-data-releases/${release}/output/etl/parquet
      destination: output/etl/parquet
  data_prep:
    - name: data_prep l2g
      source: gs://open-targets-pre-data-releases/jamesh/24.12p/output/etl/parquet/locusToGenePredictions/part-00001-3563e8c9-205f-4478-affc-7b17ede97027-c000.snappy.parquet
      destination: locusToGenePredictions.json
    - name: data_prep moa
      source: gs://open-targets-pre-data-releases/jamesh/24.12p/output/etl/parquet/mechanismOfAction/
      destination: mechanismOfAction.json
  open_search_start:
    - name: open_search_start os-pos
      service_name: "os-pos"
      volume_data: "es/data"
      volume_logs: "es/logs"
      volume_creds: "pos-gac.json"
      snapshot_name: "platform-opensearch-snapshots"
      snapshot_bucket: "open-targets-pre-data-releases"
      snapshot_base_path: "snapshots"
      opensearch_java_opts: "-Xms2g -Xmx4g"
  ot_croissant:
    - name: ot_croissant generate release metadata
      ftp_address: http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/${release}/output/etl/parquet/
      gcp_address: gs://open-targets-data-releases/${release}/output/etl/parquet/
      date_published: "2025-02-12"
      dataset_paths:
        - output/etl/parquet/AOTFClickhouse
        - output/etl/parquet/associationByDatasourceDirect
        - output/etl/parquet/associationByDatasourceIndirect
        - output/etl/parquet/associationByDatatypeDirect
        - output/etl/parquet/associationByDatatypeIndirect
        - output/etl/parquet/associationByOverallDirect
        - output/etl/parquet/associationByOverallIndirect
        - output/etl/parquet/baselineExpression
        - output/etl/parquet/biosample
        - output/etl/parquet/colocalisation/coloc
        - output/etl/parquet/colocalisation/ecaviar
        - output/etl/parquet/credibleSet
        - output/etl/parquet/diseaseToPhenotype
        - output/etl/parquet/diseases
        - output/etl/parquet/drugWarnings
        - output/etl/parquet/ebisearchAssociations
        - output/etl/parquet/ebisearchEvidence
        - output/etl/parquet/errors/evidence
        - output/etl/parquet/errors/interaction
        - output/etl/parquet/errors/mousePhenotypes
        - output/etl/parquet/evidence
        - output/etl/parquet/facetSearchDisease
        - output/etl/parquet/facetSearchTarget
        - output/etl/parquet/fda/adverseDrugReactions
        - output/etl/parquet/fda/adverseTargetReactions
        - output/etl/parquet/fda/significantAdverseDrugReactions
        - output/etl/parquet/fda/significantAdverseTargetReactions
        - output/etl/parquet/go
        - output/etl/parquet/gwasIndex
        - output/etl/parquet/hpo
        - output/etl/parquet/indication
        - output/etl/parquet/interaction
        - output/etl/parquet/interactionEvidence
        - output/etl/parquet/knownDrugsAggregated
        - output/etl/parquet/literature/W2VModel/
        - output/etl/parquet/literature/cooccurrences
        - output/etl/parquet/literature/epmcCooccurrences
        - output/etl/parquet/literature/failedCooccurrences
        - output/etl/parquet/literature/failedMatches
        - output/etl/parquet/literature/literatureIndex
        - output/etl/parquet/literature/literatureSentences
        - output/etl/parquet/literature/matches
        - output/etl/parquet/literature/trainingSet
        - output/etl/parquet/literature/vectors
        - output/etl/parquet/locusToGeneModel
        - output/etl/parquet/locusToGenePredictions
        - output/etl/parquet/mechanismOfAction
        - output/etl/parquet/molecule
        - output/etl/parquet/mousePhenotypes
        - output/etl/parquet/otar_projects
        - output/etl/parquet/pharmacogenomics
        - output/etl/parquet/reactome
        - output/etl/parquet/searchDisease
        - output/etl/parquet/searchDrug
        - output/etl/parquet/searchTarget
        - output/etl/parquet/searchVariant
        - output/etl/parquet/so-inputs
        - output/etl/parquet/targetEssentiality
        - output/etl/parquet/targetPrioritisation
        - output/etl/parquet/targets
        - output/etl/parquet/variantIndex
      output: ot_croissant_metadata.json
