---
work_path: ./work
log_level: DEBUG
# release_uri: gs://open-targets-pre-data-releases/uo_test_otter
pool: 8

scratchpad:

steps:
  test:
    - name: hello_world something
      who: ME
    - name: hello_world something else
      who: YOU
