---
work_path: ./work
log_level: SUCCESS
release_uri: gs://open-targets-pre-data-releases/25.03-testrun-3/

scratchpad:
  release: "25.03-testrun-3"
steps:
  hello:
    - name: hello_world bla bla
  download_data:
    - name: sync_bucket etl output files
      source: gs://open-targets-pre-data-releases/${release}/output
      destination: release_data
  data_prep:
    - name: data_prep l2g
      source: gs://open-targets-pre-data-releases/jamesh/24.12p/output/etl/parquet/locusToGenePredictions/part-00001-3563e8c9-205f-4478-affc-7b17ede97027-c000.snappy.parquet
      destination: locusToGenePredictions.json
    - name: data_prep moa
      source: gs://open-targets-pre-data-releases/jamesh/24.12p/output/etl/parquet/mechanismOfAction/
      destination: mechanismOfAction.json
  open_search_start:
    - name: open_search_start os-pos
      service_name: "os-pos"
      volume_data: "es/data"
      volume_logs: "es/logs"
      volume_creds: "pos-gac.json"
      snapshot_name: "platform-opensearch-snapshots"
      snapshot_bucket: "open-targets-pre-data-releases"
      snapshot_base_path: "snapshots"
      opensearch_java_opts: "-Xms2g -Xmx4g"
  ot_croissant:
    - name: ot_croissant generate release metadata
      ftp_address: http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/${release}/output/
      gcp_address: gs://open-targets-data-releases/${release}/output/
      date_published: "2025-02-12"
      dataset_path: release_data
      output: webapp/downloads.json
