---
work_path: ./work
log_level: SUCCESS

scratchpad:
  release: "2503-testrun-2"
steps:
  hello:
    - name: hello_world bla bla
  download_data:
    - name: sync_bucket etl output files
      source: gs://open-targets-pre-data-releases/${release}/output
      destination: output/etl/parquet
  data_prep:
    - name: data_prep l2g
      source: gs://open-targets-pre-data-releases/jamesh/24.12p/output/etl/parquet/locusToGenePredictions/part-00001-3563e8c9-205f-4478-affc-7b17ede97027-c000.snappy.parquet
      destination: locusToGenePredictions.json
    - name: data_prep moa
      source: gs://open-targets-pre-data-releases/jamesh/24.12p/output/etl/parquet/mechanismOfAction/
      destination: mechanismOfAction.json
  open_search_start:
    - name: open_search_start os-pos
      service_name: "os-pos"
      volume_data: "es/data"
      volume_logs: "es/logs"
      volume_creds: "pos-gac.json"
      snapshot_name: "platform-opensearch-snapshots"
      snapshot_bucket: "open-targets-pre-data-releases"
      snapshot_base_path: "snapshots"
      opensearch_java_opts: "-Xms2g -Xmx4g"
  ot_croissant:
    - name: ot_croissant generate release metadata
      ftp_address: http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/${release}/output/etl/parquet/
      gcp_address: gs://open-targets-data-releases/${release}/output/etl/parquet/
      date_published: "2025-02-12"
      dataset_paths:
        - output/etl/parquet/association_by_datasource_direct
        - output/etl/parquet/association_by_datasource_indirect
        - output/etl/parquet/association_by_datatype_direct
        - output/etl/parquet/association_by_datatype_indirect
        - output/etl/parquet/association_by_overall_indirect
        - output/etl/parquet/association_overall_direct
        - output/etl/parquet/biosample
        - output/etl/parquet/colocalisation
        - output/etl/parquet/credible_set
        - output/etl/parquet/disease
        - output/etl/parquet/disease_hpo
        - output/etl/parquet/disease_phenotype
        - output/etl/parquet/drug_indication
        - output/etl/parquet/drug_mechanism_of_action
        - output/etl/parquet/drug_molecule
        - output/etl/parquet/drug_warning
        - output/etl/parquet/evidence
        - output/etl/parquet/expression
        - output/etl/parquet/go
        - output/etl/parquet/interaction
        - output/etl/parquet/interaction_evidence
        - output/etl/parquet/known_drug
        - output/etl/parquet/l2g_prediction
        - output/etl/parquet/literature
        - output/etl/parquet/literature_vector
        - output/etl/parquet/openfda_significant_adverse_drug_reactions
        - output/etl/parquet/openfda_significant_adverse_target_reactions
        - output/etl/parquet/pharmacogenomics
        - output/etl/parquet/reactome
        - output/etl/parquet/so
        - output/etl/parquet/study
        - output/etl/parquet/target
        - output/etl/parquet/target_essentiality
        - output/etl/parquet/target_prioritisation
        - output/etl/parquet/target_validation/mouse_phenotypes
        - output/etl/parquet/variant
      output: ot_croissant_metadata.json
