---
work_path: ./work
log_level: SUCCESS

scratchpad:
  release: "2503-testrun-3"
steps:
  hello:
    - name: hello_world bla bla
  download_data:
    - name: sync_bucket etl output files
      source: gs://open-targets-pre-data-releases/${release}/output
      destination: release_data
  data_prep:
    - name: data_prep l2g
      source: gs://open-targets-pre-data-releases/jamesh/24.12p/output/etl/parquet/locusToGenePredictions/part-00001-3563e8c9-205f-4478-affc-7b17ede97027-c000.snappy.parquet
      destination: locusToGenePredictions.json
    - name: data_prep moa
      source: gs://open-targets-pre-data-releases/jamesh/24.12p/output/etl/parquet/mechanismOfAction/
      destination: mechanismOfAction.json
  open_search_start:
    - name: open_search_start os-pos
      service_name: "os-pos"
      volume_data: "es/data"
      volume_logs: "es/logs"
      volume_creds: "pos-gac.json"
      snapshot_name: "platform-opensearch-snapshots"
      snapshot_bucket: "open-targets-pre-data-releases"
      snapshot_base_path: "snapshots"
      opensearch_java_opts: "-Xms2g -Xmx4g"
  ot_croissant:
    - name: ot_croissant generate release metadata
      ftp_address: http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/${release}/output/
      gcp_address: gs://open-targets-data-releases/${release}/output/
      date_published: "2025-02-12"
      dataset_paths:
        - release_data/association_by_datasource_direct
        - release_data/association_by_datasource_indirect
        - release_data/association_by_datatype_direct
        - release_data/association_by_datatype_indirect
        - release_data/association_by_overall_indirect
        - release_data/association_overall_direct
        - release_data/biosample
        - release_data/colocalisation_coloc
        - release_data/colocalisation_ecaviar
        - release_data/credible_set
        - release_data/disease
        - release_data/disease_hpo
        - release_data/disease_phenotype
        - release_data/drug_indication
        - release_data/drug_mechanism_of_action
        - release_data/drug_molecule
        - release_data/drug_warning
        - release_data/evidence
        - release_data/expression
        - release_data/go
        - release_data/interaction
        - release_data/interaction_evidence
        - release_data/known_drug
        - release_data/l2g_prediction
        - release_data/literature
        - release_data/literature_vector
        - release_data/openfda_significant_adverse_drug_reactions
        - release_data/openfda_significant_adverse_target_reactions
        - release_data/pharmacogenomics
        - release_data/reactome
        - release_data/so
        - release_data/study
        - release_data/target
        - release_data/target_essentiality
        - release_data/target_prioritisation
        - release_data/mouse_phenotype
        - release_data/variant
      output: ot_croissant_metadata.json
