CREATE TABLE if not exists colocalisation_log (
    `leftStudyLocusId` String,
    `rightStudyLocusId` String,
    `rightStudyType` Enum(
        'tuqtl',
        'pqtl',
        'eqtl',
        'sqtl',
        'sctuqtl',
        'scpqtl',
        'sceqtl',
        'scsqtl',
        'gwas'
    ),
    `chromosome` Enum(
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        'X',
        'Y',
        'MT'
    ),
    `colocalisationMethod` LowCardinality (String),
    `numberColocalisingVariants` UInt32,
    `h3` Float64,
    `h4` Float64,
    `clpp` Float64,
    `betaRatioSignAverage` Float64
) engine = Log;