CREATE TABLE if not exists credible_sets_log (
    `studyLocusId` String,
    `variantId` String,
    `chromosome` Enum(
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        'X',
        'Y',
        'MT'
    ),
    `position` UInt32,
    `region` Nullable (String),
    `studyId` String,
    `beta` Nullable (Float64),
    `zScore` Nullable (Float64),
    `pValueMantissa` Float64,
    `pValueExponent` Int32,
    `effectAlleleFrequencyFromSource` Nullable (Float64),
    `standardError` Nullable (Float64),
    `subStudyDescription` Nullable (String),
    `qualityControls` Array (String),
    `finemappingMethod` LowCardinality (String),
    `credibleSetIndex` Nullable (UInt8),
    `credibleSetlog10BF` Nullable (Float64),
    `purityMeanR2` Nullable (Float64),
    `purityMinR2` Nullable (Float64),
    `locusStart` Nullable (Int32),
    `locusEnd` Nullable (Int32),
    `sampleSize` Nullable (UInt32),
    `locus` Array (
        Tuple (
            `is95CredibleSet` Bool,
            `is99CredibleSet` Bool,
            `logBF` Nullable (Float64),
            `posteriorProbability` Float64,
            `variantId` String,
            `pValueMantissa` Nullable (Float64),
            `pValueExponent` Nullable (Int32),
            `beta` Nullable (Float64),
            `standardError` Nullable (Float64),
            `r2Overall` Nullable (Float64)
        )
    ),
    `ldSet` Array (
        Tuple (
            `tagVariantId` String,
            `r2Overall` Float64
        )
    ),
    `studyType` Enum(
        'tuqtl',
        'pqtl',
        'eqtl',
        'sqtl',
        'sctuqtl',
        'scpqtl',
        'sceqtl',
        'scsqtl',
        'gwas'
    ),
    `qtlGeneId` Nullable (String),
    `confidence` LowCardinality (String),
    `isTransQtl` Nullable (Bool)
) engine = Log;