---
work_path: ./work
log_level: TRACE
steps:
  data_prep:
    - name: data_prep l2g
      source: gs://open-targets-pre-data-releases/jamesh/24.12p/output/etl/parquet/locusToGenePredictions/part-00001-3563e8c9-205f-4478-affc-7b17ede97027-c000.snappy.parquet
      destination: locusToGenePredictions.json
    - name: data_prep moa
      source: gs://open-targets-pre-data-releases/jamesh/24.12p/output/etl/parquet/mechanismOfAction/
      destination: mechanismOfAction.json
  open_search_start:
    - name: open_search_start opensearch start
      service_name: "os-pos"
      volume_data: "es/data"
      volume_logs: "es/logs"
      volume_creds: "pos-gac.json"
      snapshot_repository_name: "platform-opensearch-snapshots"
      snapshot_bucket: "open-targets-pre-data-releases"
      snapshot_base_path: "jamesh/snapshots"
      opensearch_java_opts: "-Xms2g -Xmx4g"
  open_search_create_index:
    - name: open_search_create_index opensearch create index l2g
      service_name: "os-pos"
      index: "l2g_predictions"
      mappings: "config/opensearch/l2g.json"
  open_search_load:
    - name: open_search_load opensearch load l2g
      service_name: "os-pos"
      index: "l2g_predictions"
      data: "locusToGenePredictions.json"
  open_search_snapshot:
    - name: open_search_snapshot opensearch snapshot
      snapshot_repository_name: "platform-opensearch-snapshots"
      snapshot_name: "2"
      indices: "*,-.*"
  open_search_restore:
    - name: open_search_restore opensearch restore
      snapshot_repository_name: "platform-opensearch-snapshots"
      snapshot_name: "2"
  open_search_stop:
    - name: open_search_stop opensearch stop
      service_name: "os-pos"
  open_search_load_all:
    - name: open_search_start opensearch start
      volume_data: "es/data"
      volume_logs: "es/logs"
      volume_creds: "pos-gac.json"
      snapshot_repository_name: "platform-opensearch-snapshots"
      snapshot_bucket: "open-targets-pre-data-releases"
      snapshot_base_path: "jamesh/snapshots"
      opensearch_java_opts: "-Xms2g -Xmx4g"
    - name: explode load all datasets
      foreach:
        - pharmacogenomics
        - diseases
      do: 
        - name: data_prep ${each} data prep
          source: "gs://open-targets-pre-data-releases/jamesh/24.12p/output/etl/parquet/${each}/*.parquet"
          destination: ${each}.jsonl
        - name: open_search_create_index opensearch create index ${each}
          index: ${each} # need to inject value here
          mappings: "config/opensearch/${each}.json" # one for each 
          requires:
            - open_search_start opensearch start
        - name: open_search_load opensearch load ${each}
          index: ${each}
          data: ${each}.jsonl
          requires:
            - open_search_create_index opensearch create index ${each}